### PR TITLE
TimestampBehavior for twig, less and html models

### PR DESCRIPTION
**Pull request by handcode**
This PR adds the created_at && updated_at table cols and attach [yii\behaviors\TimestampBehavior](https://www.yiiframework.com/doc/api/2.0/yii-behaviors-timestampbehavior) via BaseModel for twig, less and html models.

### CODE REVIEW

**Comment by eluhr** [comment]
LGTM

**Comment by handcode** [comment]
@eluhr please check psql ;-)

**Comment by eluhr** [comment]
> @eluhr please check psql ;-)

The only critical line in my opinion is [line 53](https://github.com/dmstr/yii2-prototype-module/pull/21/files#diff-9ffbf7688271c3a1c98312d1e5194ebfa862348cff4dff0284fb959c0be98095R53) but the function for date and time in MySQL and Postgres are basically the same: [NOW](https://www.postgresqltutorial.com/postgresql-now/). So i see no problems.

**Comment by handcode** [comment]
@eluhr Thanks, just wanted to double check.

**Pull request merged**
